# Generated by Django 5.0 on 2024-01-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_publicationlink_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
